[book]
authors = ["TeoDev1611"]
language = "en"
multilingual = false
src = "src"
title = "Moldy Book and News"

[output.html]
theme = "/theme"
copy-fonts = false
mathjax-support = true
site-url = "/book/"
git-repository-url = "https://github.com/Moldy-Community/book"
edit-url-template = "https://github.com/Moldy-Community/book/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[build]
build-dir = "build"

