name: Format Markdowns

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install mdformat
        run: python -m pip install --upgrade mdformat

      - name: Format the file
        run : mdformat ./src
      - name: Export the name on deploy
        run : |
          echo "Book deployed in https://moldy-book.netlify.app/"