  
name: Ci

on: [push, pull_request]

jobs:
  book:
    name: Book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Cache Cargo Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/book.toml') }}

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tools
        run: cargo install mdbook mdbook-linkcheck || true

      - name: Test Book
        run: mdbook test

      - name: Build Book
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') }}
        run: mdbook build

      - name: Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') }}
        run: |
          git checkout -b gh-pages
          mkdir -p /tmp/diamonds-book
          cp -rf .git build/html/* /tmp/diamonds-book
          cd /tmp/diamonds-book
          git add .
          git config user.name ${{ secrets.GIT_USER_NAME }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}
          git commit -am "Auto release of \`${{ github.workflow }}\` workflow with run id \`${{ github.run_id }}\`"
          git push -f origin gh-pages